"""followers

Revision ID: 40f74b4f4225
Revises: 3f8de6b5e9b4
Create Date: 2020-05-23 19:27:48.891300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40f74b4f4225"
down_revision = "3f8de6b5e9b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["followed_id"], ["user.id"],),
        sa.ForeignKeyConstraint(["follower_id"], ["user.id"],),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
